networks:
  lamp:

volumes:
  mysql:

services:
  web:
    build: './build'
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
      - "443:443"
      - "8888:10000"
    links:
      - db
    volumes:
      - ./apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./wwwroot:/var/www/html
    networks:
      - lamp

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lamp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
    networks:
      - lamp
  